(()=>{
const C=window.TRAILGUIDE_CONFIG;const P=C.LOCAL_PREFIX;
const sample={format:"hikingguide",format_version:1,id:"ch-gr-lenzerheide",country:"Switzerland",country_code:"CH",region:"Graubünden",destination:"Lenzerheide",summary:"High valley resort with lake, forest and mountain walking. This starter guide focuses on short, easy October options.",center:{lat:46.727,lng:9.557},best_season:"May–October; check snow and lift operations in shoulder season",access:"Train to Chur, then PostAuto to Lenzerheide. Road access via Chur or Tiefencastel.",sources:["https://arosalenzerheide.swiss/","https://www.outdooractive.com/","https://www.komoot.com/"],routes:[
{id:"heidsee-round",name:"Heidsee lake round",distance_km:4.5,duration_min:41,ascent_m:24,descent_m:24,difficulty:"Easy",activity:"Walking",start:{name:"Heidsee / Lenzerheide",lat:46.729339,lng:9.555899},highlights:["Lake","Rothorn views","Very flat"],description:"Short lakeside circuit with almost no climbing; useful as an easy autumn option.",source_url:"https://www.outdooractive.com/en/route/trail-running/arosa-lenzerheide/lake-round/10466501/",gpx_drive:null},
{id:"sporz-loop",name:"Sporz Rundgang",distance_km:3.87,duration_min:69,ascent_m:120,descent_m:120,difficulty:"Easy",activity:"Hiking",start:{name:"Val Sporz",lat:46.72547,lng:9.54772},highlights:["Maiensäss village","Panorama","Loop"],description:"Short circular walk through the Sporz area with traditional settlement scenery and open views.",source_url:"https://www.komoot.com/de-de/smarttour/e2386820283/sporz-rundgang",gpx_drive:null},
{id:"lantsch-bual",name:"Lantsch Bual loop",distance_km:4.94,duration_min:85,ascent_m:120,descent_m:120,difficulty:"Easy",activity:"Hiking",start:{name:"Lantsch/Lenz",lat:46.692258,lng:9.558145},highlights:["Forest","Quiet terrain","Autumn"],description:"Easy forest-oriented loop in the Lantsch/Lenz area.",source_url:"https://www.komoot.com/collection/3549098/diverse-natural-beauty-autumn-hiking-in-lenzerheide",gpx_drive:null}
]};
function jget(k,f){try{const r=localStorage.getItem(P+k);return r?JSON.parse(r):f}catch(e){return f}}
function jset(k,v){localStorage.setItem(P+k,JSON.stringify(v));if(!window.__tgApplyingCloud)window.dispatchEvent(new CustomEvent("trailguide:localchange",{detail:{key:P+k}}))}
let destinations=jget("destinations",[]),trips=jget("trips",[]),state=jget("state",{});
if(!destinations.length){destinations=[sample];jset("destinations",destinations)}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}window.toast=toast;
function save(){jset("destinations",destinations);jset("trips",trips);renderAll()}
function page(name){$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));if(name==='map')setTimeout(renderGlobalMap,50);scrollTo(0,0)}window.TrailGuideNav={page};
$$('[data-nav]').forEach(b=>b.onclick=()=>page(b.dataset.nav));$$('[data-action]').forEach(b=>b.onclick=()=>handleAction(b.dataset.action));
function handleAction(a){if(a==='destinations'||a==='trips'||a==='map'||a==='more')page(a);if(a==='import')$('#importInput').click();if(a==='export')exportBackup()}
function renderHome(){const hikes=destinations.reduce((n,d)=>n+(d.routes?.length||0),0);$('#homeDestinationCount').textContent=`${destinations.length} destination${destinations.length===1?'':'s'}`;$('#homeHikeCount').textContent=`${hikes} hike${hikes===1?'':'s'}`;$('#homeTripCount').textContent=`${trips.length} trip${trips.length===1?'':'s'}`;const d=destinations[0];$('#featuredDestination').innerHTML=d?destinationCard(d):'<p class="muted">Import your first Hiking Guide.</p>';$('#aboutVersion').textContent=`${C.APP_NAME} v${C.APP_VERSION}`}
function destinationCard(d){return `<article class="destination-card"><div class="eyebrow">${esc(d.country)} · ${esc(d.region)}</div><h3>${esc(d.destination)}</h3><div class="card-meta">${d.routes?.length||0} hikes · ${esc(d.best_season||'')}</div><p>${esc(d.summary||'')}</p><div class="btnrow"><button class="primary" onclick="TrailGuide.openDestination('${esc(d.id)}')">Open destination</button></div></article>`}
function renderDestinations(){const q=($('#destinationSearch')?.value||'').toLowerCase();const filtered=destinations.filter(d=>JSON.stringify(d).toLowerCase().includes(q));const countries={};filtered.forEach(d=>{countries[d.country]??={};countries[d.country][d.region]??=[];countries[d.country][d.region].push(d)});$('#destinationLibrary').innerHTML=Object.entries(countries).map(([c,regs])=>`<details class="geo-group" open><summary>${esc(c)}</summary>${Object.entries(regs).map(([r,ds])=>`<details class="geo-group" open><summary>${esc(r)}</summary>${ds.map(destinationCard).join('')}</details>`).join('')}</details>`).join('')||'<p class="muted">No destinations found.</p>'}
$('#destinationSearch').oninput=renderDestinations;
function openDestination(id){const d=destinations.find(x=>x.id===id);if(!d)return;state.lastDestination=id;jset('state',state);$('#destinationShell').innerHTML=`<div class="destination-hero"><div class="eyebrow">${esc(d.country)} · ${esc(d.region)}</div><h1>${esc(d.destination)}</h1><p>${esc(d.summary||'')}</p></div><div class="section"><div class="status-card"><b>Access</b><span>${esc(d.access||'No access notes yet.')}</span></div><div class="status-card" style="margin-top:8px"><b>Best season</b><span>${esc(d.best_season||'Not specified')}</span></div><div class="section-head" style="margin-top:18px"><h2>Hikes</h2><button class="secondary" onclick="TrailGuide.addRoute('${esc(id)}')">＋ Add route</button></div>${(d.routes||[]).map(r=>routeCard(d,r)).join('')||'<p class="muted">No hikes yet.</p>'}<div class="section-head" style="margin-top:18px"><h2>Map</h2></div><div id="destinationMap" class="mapbox"></div><div class="btnrow"><button class="secondary" onclick="TrailGuide.attachGPX('${esc(id)}')">Add / back up GPX</button><button class="secondary" onclick="TrailGuide.uploadDocument('destination','${esc(id)}')">Upload document to Drive</button></div></div>`;page('destination');setTimeout(()=>renderDestinationMap(d),70)}
function routeCard(d,r){return `<article class="route-card"><h3>${esc(r.name)}</h3><div class="card-meta">${Number(r.distance_km||0).toFixed(1)} km · ${Math.round(r.duration_min||0)} min · +${Math.round(r.ascent_m||0)} m · ${esc(r.difficulty||'')}</div><div class="tags">${(r.highlights||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="btnrow"><button class="primary" onclick="TrailGuide.openRoute('${esc(d.id)}','${esc(r.id)}')">Details</button>${r.source_url?`<a class="secondary" target="_blank" href="${esc(r.source_url)}">Source ↗</a>`:''}</div></article>`}
function openRoute(did,rid){const d=destinations.find(x=>x.id===did),r=d?.routes?.find(x=>x.id===rid);if(!r)return;$('#routeShell').innerHTML=`<div class="destination-hero"><div class="eyebrow">${esc(d.destination)} · ${esc(r.activity||'Hiking')}</div><h1>${esc(r.name)}</h1><p>${esc(r.description||'')}</p></div><div class="section"><div class="stats"><div class="stat"><b>${Number(r.distance_km||0).toFixed(1)} km</b><small>Distance</small></div><div class="stat"><b>${Math.round(r.duration_min||0)} min</b><small>Duration</small></div><div class="stat"><b>+${Math.round(r.ascent_m||0)} m</b><small>Ascent</small></div><div class="stat"><b>${esc(r.difficulty||'')}</b><small>Difficulty</small></div></div><div class="status-card"><b>Start</b><span>${esc(r.start?.name||'')} · ${r.start?.lat||''}, ${r.start?.lng||''}</span></div><div class="btnrow">${r.source_url?`<a class="primary" target="_blank" href="${esc(r.source_url)}">Open route source ↗</a>`:''}<a class="secondary" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${r.start?.lat||''},${r.start?.lng||''}">Google Maps</a><button class="secondary" onclick="TrailGuide.attachGPX('${esc(did)}','${esc(rid)}')">${r.gpx_drive?'Replace GPX':'Add GPX'}</button></div>${r.gpx_drive?`<div class="file-row"><b>GPX backed up on Drive</b><div class="card-meta">${esc(r.gpx_drive.name||'route.gpx')}</div><a class="secondary" target="_blank" href="${esc(r.gpx_drive.webViewLink||'#')}">Open in Drive ↗</a></div>`:''}</div>`;page('route')}
function renderTrips(){const root=$('#tripLibrary');root.innerHTML=trips.length?trips.map(t=>`<article class="trip-card"><div class="eyebrow">${esc(t.country||'Trip')}</div><h3>${esc(t.name)}</h3><div class="card-meta">${esc(t.start_date||'')} ${t.end_date?'→ '+esc(t.end_date):''}</div><p>${esc(t.notes||'')}</p><div class="btnrow"><button class="primary" onclick="TrailGuide.openTrip('${esc(t.id)}')">Open trip</button></div></article>`).join(''):'<p class="muted">No trips yet.</p>'}
$('#newTripBtn').onclick=()=>editTrip();
function editTrip(t=null){showDialog(t?'Edit trip':'New trip',`<div class="form-grid"><label class="field full"><span>Name</span><input id="fName" value="${esc(t?.name||'')}"></label><label class="field"><span>Country</span><input id="fCountry" value="${esc(t?.country||'')}"></label><label class="field"><span>Region</span><input id="fRegion" value="${esc(t?.region||'')}"></label><label class="field"><span>Start date</span><input id="fStart" type="date" value="${esc(t?.start_date||'')}"></label><label class="field"><span>End date</span><input id="fEnd" type="date" value="${esc(t?.end_date||'')}"></label><label class="field full"><span>Notes</span><textarea id="fNotes">${esc(t?.notes||'')}</textarea></label></div><div class="btnrow"><button class="primary" id="saveTripDialog">Save trip</button></div>`);$('#saveTripDialog').onclick=()=>{const obj={...(t||{}),format:'travelplan',format_version:1,id:t?.id||crypto.randomUUID(),name:$('#fName').value.trim()||'Untitled trip',country:$('#fCountry').value.trim(),region:$('#fRegion').value.trim(),start_date:$('#fStart').value,end_date:$('#fEnd').value,notes:$('#fNotes').value,documents:t?.documents||[],destination_ids:t?.destination_ids||[]};if(t){trips[trips.findIndex(x=>x.id===t.id)]=obj}else trips.push(obj);save();closeDialog();page('trips')}}
function openTrip(id){const t=trips.find(x=>x.id===id);if(!t)return;$('#tripShell').innerHTML=`<div class="destination-hero"><div class="eyebrow">${esc(t.country||'Travel')}</div><h1>${esc(t.name)}</h1><p>${esc(t.start_date||'')} ${t.end_date?'→ '+esc(t.end_date):''}</p></div><div class="section"><div class="status-card"><b>Notes</b><span>${esc(t.notes||'No notes yet.')}</span></div><div class="section-head" style="margin-top:18px"><h2>Linked hiking destinations</h2><button class="secondary" onclick="TrailGuide.linkDestination('${esc(id)}')">＋ Link</button></div>${(t.destination_ids||[]).map(did=>{const d=destinations.find(x=>x.id===did);return d?destinationCard(d):''}).join('')||'<p class="muted">No hiking destination linked.</p>'}<div class="section-head" style="margin-top:18px"><h2>Travel documents</h2><button class="secondary" onclick="TrailGuide.uploadDocument('trip','${esc(id)}')">＋ Upload to Drive</button></div>${(t.documents||[]).map(f=>`<div class="file-row"><b>${esc(f.name)}</b><div class="card-meta">Google Drive</div><a target="_blank" class="secondary" href="${esc(f.webViewLink||'#')}">Open ↗</a></div>`).join('')||'<p class="muted">No documents yet.</p>'}<div class="btnrow"><button class="secondary" onclick="TrailGuide.editTrip('${esc(id)}')">Edit trip</button></div></div>`;page('trip')}
function linkDestination(tid){const t=trips.find(x=>x.id===tid);showDialog('Link hiking destination',destinations.map(d=>`<label class="file-row"><input type="checkbox" class="linkDest" value="${esc(d.id)}" ${(t.destination_ids||[]).includes(d.id)?'checked':''}> <b>${esc(d.country)} · ${esc(d.region)} · ${esc(d.destination)}</b></label>`).join('')+`<div class="btnrow"><button class="primary" id="saveLinks">Save</button></div>`);$('#saveLinks').onclick=()=>{t.destination_ids=$$('.linkDest:checked').map(x=>x.value);save();closeDialog();openTrip(tid)}}
function addRoute(did){const d=destinations.find(x=>x.id===did);showDialog('Add hike',`<div class="form-grid"><label class="field full"><span>Name</span><input id="rName"></label><label class="field"><span>Distance km</span><input id="rDist" type="number" step="0.1"></label><label class="field"><span>Duration min</span><input id="rDur" type="number"></label><label class="field"><span>Ascent m</span><input id="rAsc" type="number"></label><label class="field"><span>Difficulty</span><select id="rDiff"><option>Easy</option><option>Moderate</option><option>Difficult</option></select></label><label class="field"><span>Start lat</span><input id="rLat" type="number" step="any"></label><label class="field"><span>Start lng</span><input id="rLng" type="number" step="any"></label><label class="field full"><span>Description</span><textarea id="rDesc"></textarea></label></div><div class="btnrow"><button class="primary" id="saveRoute">Save hike</button></div>`);$('#saveRoute').onclick=()=>{d.routes??=[];d.routes.push({id:crypto.randomUUID(),name:$('#rName').value||'New hike',distance_km:+$('#rDist').value||0,duration_min:+$('#rDur').value||0,ascent_m:+$('#rAsc').value||0,difficulty:$('#rDiff').value,start:{name:'Start',lat:+$('#rLat').value||d.center?.lat,lng:+$('#rLng').value||d.center?.lng},description:$('#rDesc').value,highlights:[]});save();closeDialog();openDestination(did)}}
function renderDestinationMap(d){const el=$('#destinationMap');if(!el||!window.L)return;el.innerHTML='';const m=L.map(el).setView([d.center?.lat||46.8,d.center?.lng||9.5],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(m);const pts=[];(d.routes||[]).forEach(r=>{if(r.start?.lat&&r.start?.lng){L.marker([r.start.lat,r.start.lng]).addTo(m).bindPopup(`<b>${esc(r.name)}</b><br>${r.distance_km||0} km`);pts.push([r.start.lat,r.start.lng])}});if(pts.length)m.fitBounds(pts,{padding:[30,30]})}
let globalMap;function renderGlobalMap(){const el=$('#globalMap');if(!el||!window.L)return;if(globalMap){globalMap.remove();globalMap=null}globalMap=L.map(el).setView([46.8,8.2],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(globalMap);const pts=[];destinations.forEach(d=>{if(d.center?.lat&&d.center?.lng){L.marker([d.center.lat,d.center.lng]).addTo(globalMap).bindPopup(`<b>${esc(d.destination)}</b><br>${esc(d.region)}, ${esc(d.country)}`).on('click',()=>{});pts.push([d.center.lat,d.center.lng])}});if(pts.length)globalMap.fitBounds(pts,{padding:[30,30]})}
function showDialog(title,html){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=html;$('#dialog').classList.add('open')}function closeDialog(){$('#dialog').classList.remove('open')}$('#dialogClose').onclick=closeDialog;$('#dialog').onclick=e=>{if(e.target===$('#dialog'))closeDialog()};
async function importFiles(files){for(const f of files){try{const name=f.name.toLowerCase();if(name.endsWith('.zip')){const z=await JSZip.loadAsync(f);for(const [n,e] of Object.entries(z.files)){if(e.dir)continue;const blob=await e.async('blob');await importFiles([new File([blob],n)])}}else if(name.endsWith('.gpx')){toast('GPX files are attached to a route from the route screen.')}else{const data=JSON.parse(await f.text());if(data.format==='hikingguide'){const i=destinations.findIndex(x=>x.id===data.id);i>=0?destinations[i]=data:destinations.push(data)}else if(data.format==='travelplan'){const i=trips.findIndex(x=>x.id===data.id);i>=0?trips[i]=data:trips.push(data)}else throw new Error('Unknown TrailGuide format')}}catch(e){console.error(e);toast(`Could not import ${f.name}`)}}save();toast('Import complete')}
$('#importInput').onchange=e=>{importFiles([...e.target.files]);e.target.value=''};
async function exportBackup(){const blob=new Blob([JSON.stringify({format:'trailguide_backup',format_version:1,exported_at:new Date().toISOString(),destinations,trips},null,2)],{type:'application/json'});download(blob,`TrailGuide_backup_${new Date().toISOString().slice(0,10)}.json`)}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
let pendingGPX={};function attachGPX(did,rid=''){pendingGPX={did,rid};$('#gpxInput').click()}$('#gpxInput').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{const d=destinations.find(x=>x.id===pendingGPX.did);const r=pendingGPX.rid?d?.routes?.find(x=>x.id===pendingGPX.rid):null;const saved=await window.TrailGuideDrive.uploadGPX({destination:d,route:r,file:f});if(r)r.gpx_drive=saved;else{d.gpx_files??=[];d.gpx_files.push(saved)}save();toast('GPX backed up to Google Drive');if(r)openRoute(d.id,r.id);else openDestination(d.id)}catch(err){toast(err.message);console.error(err)}};
let pendingDoc={};function uploadDocument(type,id){pendingDoc={type,id};$('#documentInput').click()}$('#documentInput').onchange=async e=>{const files=[...e.target.files];e.target.value='';if(!files.length)return;try{for(const f of files){const saved=await window.TrailGuideDrive.uploadDocument({type:pendingDoc.type,id:pendingDoc.id,file:f,destinations,trips});if(pendingDoc.type==='trip'){const t=trips.find(x=>x.id===pendingDoc.id);t.documents??=[];t.documents.push(saved)}else{const d=destinations.find(x=>x.id===pendingDoc.id);d.documents??=[];d.documents.push(saved)}}save();toast('Document saved to Google Drive');pendingDoc.type==='trip'?openTrip(pendingDoc.id):openDestination(pendingDoc.id)}catch(err){toast(err.message);console.error(err)}};
function replaceFromCloud(data){window.__tgApplyingCloud=true;try{if(data.destinations)destinations=data.destinations;if(data.trips)trips=data.trips;if(data.state)state=data.state;jset('destinations',destinations);jset('trips',trips);jset('state',state);renderAll()}finally{window.__tgApplyingCloud=false}}function getCloudData(){return {destinations,trips,state}}
window.TrailGuide={openDestination,openRoute,addRoute,attachGPX,uploadDocument,openTrip,editTrip:id=>editTrip(trips.find(x=>x.id===id)),linkDestination,getCloudData,replaceFromCloud,renderAll:()=>renderAll()};
function renderAll(){renderHome();renderDestinations();renderTrips()}renderAll();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(console.warn));
})();
