(()=>{
const C=window.TRAILGUIDE_CONFIG;
const SHARE_ID=new URLSearchParams(location.search).get("share");
const P=SHARE_ID?`tg_share_${SHARE_ID}_`:C.LOCAL_PREFIX;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function jget(k,f){try{const r=localStorage.getItem(P+k);return r?JSON.parse(r):f}catch(e){return f}}
function jset(k,v){localStorage.setItem(P+k,JSON.stringify(v));if(!window.__tgApplyingCloud&&!SHARE_ID)window.dispatchEvent(new CustomEvent("trailguide:localchange",{detail:{key:P+k}}))}
let destinations=jget("destinations",[]),trips=jget("trips",[]),state=jget("state",{});
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function norm(v=""){return String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)}window.toast=toast;
function validGeom(g){return Array.isArray(g)&&g.length>1&&g.every(p=>Array.isArray(p)&&p.length>=2&&Number.isFinite(+p[0])&&Number.isFinite(+p[1]))}
function normalizeGeom(g){return (g||[]).map(p=>[+p[0],+p[1]]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]))}
function preserveAttachments(oldObj,newObj){if(!oldObj)return newObj;const out={...newObj};for(const k of ["documents","gpx_files"])if(oldObj[k]&&!out[k])out[k]=oldObj[k];return out}
function mergeRoute(oldR,newR){const out={...oldR,...newR};if(oldR?.gpx_drive&&!newR.gpx_drive)out.gpx_drive=oldR.gpx_drive;if(validGeom(oldR?.gpx_geometry)&&!validGeom(newR?.gpx_geometry))out.gpx_geometry=oldR.gpx_geometry;if(oldR?.gpx_original&&!newR.gpx_original)out.gpx_original=oldR.gpx_original;if(oldR?.start&&!newR.start)out.start=oldR.start;if(oldR?.end&&!newR.end)out.end=oldR.end;return out}
function mergeGuide(oldD,newD){const out=preserveAttachments(oldD,{...oldD,...newD});const oldRoutes=oldD?.routes||[];out.routes=(newD.routes||[]).map(nr=>{const or=oldRoutes.find(r=>r.id===nr.id)||oldRoutes.find(r=>norm(r.name)===norm(nr.name));return or?mergeRoute(or,nr):nr});for(const or of oldRoutes){if(!out.routes.some(r=>r.id===or.id||norm(r.name)===norm(or.name)))out.routes.push(or)}return out}
function save(){jset("destinations",destinations);jset("trips",trips);renderAll()}
function page(name){$$(".page").forEach(x=>x.classList.toggle("active",x.dataset.page===name));$$(".bottom-nav button").forEach(x=>x.classList.toggle("active",x.dataset.nav===name));if(name==="map")setTimeout(renderGlobalMap,60);closeDrawer();scrollTo(0,0)}
window.TrailGuideNav={page};
$$("[data-nav]").forEach(b=>b.onclick=()=>page(b.dataset.nav));
$$("[data-action]").forEach(b=>b.onclick=()=>handleAction(b.dataset.action));
function handleAction(a){if(["home","destinations","trips","map","more"].includes(a))page(a);if(a==="import")$("#importInput").click();if(a==="export")exportBackup()}

function openDrawer(){$("#drawer").classList.add("open");$("#drawer").setAttribute("aria-hidden","false");$("#drawerScrim").classList.add("show")}
function closeDrawer(){$("#drawer").classList.remove("open");$("#drawer").setAttribute("aria-hidden","true");$("#drawerScrim").classList.remove("show")}
$("#menuBtn").onclick=openDrawer;$("#drawerClose").onclick=closeDrawer;$("#drawerScrim").onclick=closeDrawer;
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDrawer()});

function renderHome(){const hikes=destinations.reduce((n,d)=>n+(d.routes?.length||0),0);$("#homeDestinationCount").textContent=`${destinations.length} Ziel${destinations.length===1?"":"e"}`;$("#homeHikeCount").textContent=`${hikes} Wanderung${hikes===1?"":"en"}`;$("#homeTripCount").textContent=`${trips.length} Reise${trips.length===1?"":"n"}`;const d=destinations[0];$("#featuredDestination").innerHTML=d?destinationCard(d):'<p class="muted">Importiere deinen ersten Wander-Guide.</p>';$("#aboutVersion").textContent=`${C.APP_NAME} v${C.APP_VERSION}${SHARE_ID?" · Freigabelink":""}`}
function destinationCard(d){const tracks=(d.routes||[]).filter(r=>validGeom(r.gpx_geometry)).length;return `<article class="destination-card"><div class="eyebrow">${esc(d.country||"")} · ${esc(d.region||"")}</div><h3>${esc(d.destination||"Ziel")}</h3><div class="card-meta">${d.routes?.length||0} Wanderungen · ${tracks} vollständige GPX-Tracks</div><p>${esc(d.summary||"")}</p><div class="btnrow"><button class="primary" onclick="TrailGuide.openDestination('${esc(d.id)}')">Ziel öffnen</button></div></article>`}
function renderDestinations(){const q=($("#destinationSearch")?.value||"").toLowerCase();const filtered=destinations.filter(d=>JSON.stringify(d).toLowerCase().includes(q));const countries={};filtered.forEach(d=>{const c=d.country||"Unbekannt",r=d.region||"Andere";countries[c]??={};countries[c][r]??=[];countries[c][r].push(d)});$("#destinationLibrary").innerHTML=Object.entries(countries).map(([c,regs])=>`<details class="geo-group" open><summary>${esc(c)}</summary>${Object.entries(regs).map(([r,ds])=>`<details class="geo-group" open><summary>${esc(r)}</summary>${ds.map(destinationCard).join("")}</details>`).join("")}</details>`).join("")||'<p class="muted">Keine Ziele gefunden.</p>'}
$("#destinationSearch").oninput=renderDestinations;
function linksHtml(links=[]){if(!links.length)return '<p class="muted">Noch keine ÖV- oder Bergbahn-Links hinterlegt.</p>';return links.map(l=>`<div class="file-row"><b>${esc(l.label||l.provider||"Link")}</b><div class="card-meta">${esc(l.provider||"")} ${l.note?"· "+esc(l.note):""}</div><a class="secondary" target="_blank" rel="noopener" href="${esc(l.url||"#")}">Öffnen ↗</a></div>`).join("")}
function infoHtml(items=[]){return items.map(i=>`<div class="status-card" style="margin-top:8px"><b>${esc(i.title||"Aktuelle Information")}</b><span>${esc(i.text||"")} ${i.checked_at?`· geprüft ${esc(i.checked_at)}`:""}</span>${i.url?`<div class="btnrow"><a class="secondary" target="_blank" href="${esc(i.url)}">Quelle ↗</a></div>`:""}</div>`).join("")}
function openDestination(id){const d=destinations.find(x=>x.id===id);if(!d)return;state.lastDestination=id;jset("state",state);$("#destinationShell").innerHTML=`<div class="destination-hero"><div class="eyebrow">${esc(d.country||"")} · ${esc(d.region||"")}</div><h1>${esc(d.destination||"")}</h1><p>${esc(d.summary||"")}</p></div><div class="section"><div class="status-card"><b>Anreise & Zugang</b><span>${esc(d.access||"Noch keine Zugangsinformationen.")}</span></div>${infoHtml(d.current_info||[])}<div class="section-head" style="margin-top:18px"><h2>ÖV & Bergbahnen</h2></div>${linksHtml(d.access_links||[])}<div class="status-card" style="margin-top:8px"><b>Beste Jahreszeit</b><span>${esc(d.best_season||"Nicht angegeben")}</span></div><div class="section-head" style="margin-top:18px"><h2>Wanderungen</h2><button class="secondary" onclick="TrailGuide.addRoute('${esc(id)}')">＋ Route hinzufügen</button></div>${(d.routes||[]).map(r=>routeCard(d,r)).join("")||'<p class="muted">Noch keine Wanderungen.</p>'}<div class="section-head" style="margin-top:18px"><h2>Karte</h2></div><div id="destinationMap" class="mapbox"></div><div class="btnrow"><button class="secondary" onclick="TrailGuide.uploadDocument('destination','${esc(id)}')">Dokument auf Drive speichern</button></div><div class="card-meta">Guide zuletzt geprüft: ${esc(d.source_checked_at||"unbekannt")} · Revision ${esc(d.revision||1)}</div></div>`;page("destination");setTimeout(()=>renderDestinationMap(d),80)}
function routeCard(d,r){const has=validGeom(r.gpx_geometry);return `<article class="route-card"><h3>${esc(r.name||"Route")}</h3><div class="card-meta">${Number(r.distance_km||0).toFixed(1)} km · ${Math.round(r.duration_min||0)} min · +${Math.round(r.ascent_m||0)} m · ${esc(r.difficulty||"")}</div><div class="tags">${(r.highlights||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div><div class="${has?"gpx-ok":"gpx-warn"}">${has?`✓ Vollständiger GPX-Track · ${r.gpx_geometry.length} Punkte`:"Noch kein vollständiger GPX-Track"}</div><div class="btnrow"><button class="primary" onclick="TrailGuide.openRoute('${esc(d.id)}','${esc(r.id)}')">Details</button>${r.source_url?`<a class="secondary" target="_blank" href="${esc(r.source_url)}">Quelle ↗</a>`:""}</div></article>`}
function openRoute(did,rid){const d=destinations.find(x=>x.id===did),r=d?.routes?.find(x=>x.id===rid);if(!r)return;const has=validGeom(r.gpx_geometry);$("#routeShell").innerHTML=`<div class="destination-hero"><div class="eyebrow">${esc(d.destination||"")} · ${esc(r.activity||"Wandern")}</div><h1>${esc(r.name||"")}</h1><p>${esc(r.description||"")}</p></div><div class="section"><div class="stats"><div class="stat"><b>${Number(r.distance_km||0).toFixed(1)} km</b><small>Distanz</small></div><div class="stat"><b>${Math.round(r.duration_min||0)} min</b><small>Dauer</small></div><div class="stat"><b>+${Math.round(r.ascent_m||0)} m</b><small>Aufstieg</small></div><div class="stat"><b>${esc(r.difficulty||"")}</b><small>Schwierigkeit</small></div></div><div class="status-card"><b>Start</b><span>${esc(r.start?.name||"")} · ${fmtCoord(r.start)}</span></div><div class="status-card" style="margin-top:8px"><b>Ende</b><span>${esc(r.end?.name||r.start?.name||"")} · ${fmtCoord(r.end||r.start)}</span></div><div class="section-head" style="margin-top:18px"><h2>Routenverlauf</h2></div><div id="routeMap" class="mapbox"></div><div class="${has?"gpx-ok":"gpx-warn"}">${has?`✓ Vollständiger GPX-Track geladen · ${r.gpx_geometry.length} Trackpunkte`:"Noch kein GPX hinterlegt. Füge die GPX-Datei dieser Wanderung hinzu."}</div><div class="section-head" style="margin-top:18px"><h2>Anreise</h2></div>${linksHtml(r.access_links||d.access_links||[])}<div class="btnrow">${r.source_url?`<a class="primary" target="_blank" href="${esc(r.source_url)}">Routenquelle öffnen ↗</a>`:""}<a class="secondary" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${r.start?.lat||""},${r.start?.lng||""}">Start in Google Maps</a><button class="secondary" onclick="TrailGuide.attachGPX('${esc(did)}','${esc(rid)}')">${has?"GPX ersetzen":"GPX hinzufügen"}</button></div>${r.gpx_drive?`<div class="file-row"><b>GPX auf Google Drive gesichert</b><div class="card-meta">${esc(r.gpx_drive.name||"route.gpx")}</div><a class="secondary" target="_blank" href="${esc(r.gpx_drive.webViewLink||"#")}">In Drive öffnen ↗</a></div>`:""}<div class="card-meta">Routeninformation zuletzt geprüft: ${esc(r.source_checked_at||"unbekannt")}</div></div>`;page("route");setTimeout(()=>renderRouteMap(r),80)}
function fmtCoord(p){return p?.lat!=null&&p?.lng!=null?`${Number(p.lat).toFixed(5)}, ${Number(p.lng).toFixed(5)}`:"nicht angegeben"}
function pointIcon(label){return L.divIcon({className:"route-point-wrap",html:`<div class="route-point-icon">${label}</div>`,iconSize:[28,28],iconAnchor:[14,14]})}
function addRouteToMap(m,r,pts){const geom=normalizeGeom(r.gpx_geometry);if(validGeom(geom)){L.polyline(geom,{weight:5,opacity:.86}).addTo(m).bindPopup(`<b>${esc(r.name)}</b><br>${r.distance_km||0} km`);pts.push(...geom)}const s=r.start,e=r.end||((geom.length)?{lat:geom[geom.length-1][0],lng:geom[geom.length-1][1]}:r.start);if(s?.lat!=null&&s?.lng!=null){L.marker([s.lat,s.lng],{icon:pointIcon("A")}).addTo(m).bindPopup(`<b>Start</b><br>${esc(s.name||r.name)}`);pts.push([s.lat,s.lng])}if(e?.lat!=null&&e?.lng!=null){const different=!s||Math.abs(+e.lat-(+s.lat||0))>0.00002||Math.abs(+e.lng-(+s.lng||0))>0.00002;L.marker([e.lat,e.lng],{icon:pointIcon(different?"Z":"↻")}).addTo(m).bindPopup(`<b>${different?"Ziel":"Rundweg"}</b><br>${esc(e.name||r.name)}`);pts.push([e.lat,e.lng])}}
function baseMap(el,center=[46.8,8.2],zoom=8){const m=L.map(el).setView(center,zoom);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(m);return m}
function renderRouteMap(r){const el=$("#routeMap");if(!el||!window.L)return;el.innerHTML="";const geom=normalizeGeom(r.gpx_geometry);const center=validGeom(geom)?geom[Math.floor(geom.length/2)]:[r.start?.lat||46.8,r.start?.lng||8.2];const m=baseMap(el,center,13),pts=[];addRouteToMap(m,r,pts);if(pts.length)m.fitBounds(pts,{padding:[30,30],maxZoom:15})}
function renderDestinationMap(d){const el=$("#destinationMap");if(!el||!window.L)return;el.innerHTML="";const m=baseMap(el,[d.center?.lat||46.8,d.center?.lng||9.5],12),pts=[];(d.routes||[]).forEach(r=>addRouteToMap(m,r,pts));if(pts.length)m.fitBounds(pts,{padding:[30,30],maxZoom:15})}
let globalMap;function renderGlobalMap(){const el=$("#globalMap");if(!el||!window.L)return;if(globalMap){globalMap.remove();globalMap=null}globalMap=baseMap(el,[46.8,8.2],7);const pts=[];destinations.forEach(d=>(d.routes||[]).forEach(r=>addRouteToMap(globalMap,r,pts)));if(pts.length)globalMap.fitBounds(pts,{padding:[30,30],maxZoom:14})}

function renderTrips(){$("#tripLibrary").innerHTML=trips.length?trips.map(t=>`<article class="trip-card"><div class="eyebrow">${esc(t.country||"Reise")}</div><h3>${esc(t.name)}</h3><div class="card-meta">${esc(t.start_date||"")} ${t.end_date?"→ "+esc(t.end_date):""}</div><p>${esc(t.notes||"")}</p><div class="btnrow"><button class="primary" onclick="TrailGuide.openTrip('${esc(t.id)}')">Reise öffnen</button></div></article>`).join(""):'<p class="muted">Noch keine Reisen.</p>'}
$("#newTripBtn").onclick=()=>editTrip();
function editTrip(t=null){showDialog(t?"Reise bearbeiten":"Neue Reise",`<div class="form-grid"><label class="field full"><span>Name</span><input id="fName" value="${esc(t?.name||"")}"></label><label class="field"><span>Land</span><input id="fCountry" value="${esc(t?.country||"")}"></label><label class="field"><span>Region</span><input id="fRegion" value="${esc(t?.region||"")}"></label><label class="field"><span>Startdatum</span><input id="fStart" type="date" value="${esc(t?.start_date||"")}"></label><label class="field"><span>Enddatum</span><input id="fEnd" type="date" value="${esc(t?.end_date||"")}"></label><label class="field full"><span>Notizen</span><textarea id="fNotes">${esc(t?.notes||"")}</textarea></label></div><div class="btnrow"><button class="primary" id="saveTripDialog">Reise speichern</button></div>`);$("#saveTripDialog").onclick=()=>{const obj={...(t||{}),format:"travelplan",format_version:2,id:t?.id||crypto.randomUUID(),name:$("#fName").value.trim()||"Unbenannte Reise",country:$("#fCountry").value.trim(),region:$("#fRegion").value.trim(),start_date:$("#fStart").value,end_date:$("#fEnd").value,notes:$("#fNotes").value,documents:t?.documents||[],destination_ids:t?.destination_ids||[],updated_at:new Date().toISOString()};if(t)trips[trips.findIndex(x=>x.id===t.id)]=obj;else trips.push(obj);save();closeDialog();page("trips")}}
function openTrip(id){const t=trips.find(x=>x.id===id);if(!t)return;$("#tripShell").innerHTML=`<div class="destination-hero"><div class="eyebrow">${esc(t.country||"Reise")}</div><h1>${esc(t.name)}</h1><p>${esc(t.start_date||"")} ${t.end_date?"→ "+esc(t.end_date):""}</p></div><div class="section"><div class="status-card"><b>Notizen</b><span>${esc(t.notes||"Noch keine Notizen.")}</span></div><div class="section-head" style="margin-top:18px"><h2>Verknüpfte Wanderziele</h2><button class="secondary" onclick="TrailGuide.linkDestination('${esc(id)}')">＋ Verknüpfen</button></div>${(t.destination_ids||[]).map(did=>{const d=destinations.find(x=>x.id===did);return d?destinationCard(d):""}).join("")||'<p class="muted">Noch kein Wanderziel verknüpft.</p>'}<div class="section-head" style="margin-top:18px"><h2>Reisedokumente</h2><button class="secondary" onclick="TrailGuide.uploadDocument('trip','${esc(id)}')">＋ Auf Drive speichern</button></div>${(t.documents||[]).map(f=>`<div class="file-row"><b>${esc(f.name)}</b><div class="card-meta">Google Drive</div><a target="_blank" class="secondary" href="${esc(f.webViewLink||"#")}">Öffnen ↗</a></div>`).join("")||'<p class="muted">Noch keine Dokumente.</p>'}<div class="btnrow"><button class="secondary" onclick="TrailGuide.editTrip('${esc(id)}')">Reise bearbeiten</button></div></div>`;page("trip")}
function linkDestination(tid){const t=trips.find(x=>x.id===tid);showDialog("Wanderziele verknüpfen",destinations.map(d=>`<label class="file-row"><input type="checkbox" class="linkDest" value="${esc(d.id)}" ${(t.destination_ids||[]).includes(d.id)?"checked":""}> <b>${esc(d.country)} · ${esc(d.region)} · ${esc(d.destination)}</b></label>`).join("")+`<div class="btnrow"><button class="primary" id="saveLinks">Speichern</button></div>`);$("#saveLinks").onclick=()=>{t.destination_ids=$$(".linkDest:checked").map(x=>x.value);save();closeDialog();openTrip(tid)}}
function addRoute(did){const d=destinations.find(x=>x.id===did);showDialog("Wanderung hinzufügen",`<div class="form-grid"><label class="field full"><span>Name</span><input id="rName"></label><label class="field"><span>Distanz km</span><input id="rDist" type="number" step="0.1"></label><label class="field"><span>Dauer min</span><input id="rDur" type="number"></label><label class="field"><span>Aufstieg m</span><input id="rAsc" type="number"></label><label class="field"><span>Schwierigkeit</span><select id="rDiff"><option>Einfach</option><option>Mittel</option><option>Schwierig</option></select></label><label class="field"><span>Start Lat</span><input id="rLat" type="number" step="any"></label><label class="field"><span>Start Lng</span><input id="rLng" type="number" step="any"></label><label class="field full"><span>Beschreibung</span><textarea id="rDesc"></textarea></label></div><div class="btnrow"><button class="primary" id="saveRoute">Wanderung speichern</button></div>`);$("#saveRoute").onclick=()=>{d.routes??=[];const s={name:"Start",lat:+$("#rLat").value||d.center?.lat,lng:+$("#rLng").value||d.center?.lng};d.routes.push({id:crypto.randomUUID(),name:$("#rName").value||"Neue Wanderung",distance_km:+$("#rDist").value||0,duration_min:+$("#rDur").value||0,ascent_m:+$("#rAsc").value||0,difficulty:$("#rDiff").value,start:s,end:{...s,name:"Ziel"},description:$("#rDesc").value,highlights:[],access_links:[],gpx_geometry:[],updated_at:new Date().toISOString()});d.updated_at=new Date().toISOString();save();closeDialog();openDestination(did)}}
function showDialog(title,html){$("#dialogTitle").textContent=title;$("#dialogBody").innerHTML=html;$("#dialog").classList.add("open")}function closeDialog(){$("#dialog").classList.remove("open")}$("#dialogClose").onclick=closeDialog;$("#dialog").onclick=e=>{if(e.target===$("#dialog"))closeDialog()};

function parseGPX(text){const xml=new DOMParser().parseFromString(text,"application/xml");if(xml.querySelector("parsererror"))throw new Error("Ungültige GPX-Datei");let nodes=[...xml.getElementsByTagNameNS("*","trkpt")];if(!nodes.length)nodes=[...xml.getElementsByTagNameNS("*","rtept")];if(!nodes.length)throw new Error("Keine Trackpunkte im GPX gefunden");let pts=nodes.map(n=>[+n.getAttribute("lat"),+n.getAttribute("lon")]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));const max=4000;if(pts.length>max){const step=Math.ceil(pts.length/max);pts=pts.filter((_,i)=>i%step===0||i===pts.length-1)}return pts}
function hydrateGuide(data){(data.routes||[]).forEach(r=>{if(validGeom(r.gpx_geometry))r.gpx_geometry=normalizeGeom(r.gpx_geometry);else if(validGeom(r.gpx?.geometry))r.gpx_geometry=normalizeGeom(r.gpx.geometry);else if(validGeom(r.track))r.gpx_geometry=normalizeGeom(r.track);else if(typeof r.gpx_text==="string"&&r.gpx_text.trim()){try{r.gpx_geometry=parseGPX(r.gpx_text);r.gpx_original=r.gpx_text}catch(e){console.warn("Embedded GPX could not be parsed",e)}}});return data}
function guideKey(d){return d.id||`${norm(d.country_code||d.country)}:${norm(d.region)}:${norm(d.destination)}`}
function tripKey(t){return t.id||`${norm(t.name)}:${t.start_date||""}:${t.end_date||""}`}
function upsertGuide(data){data=hydrateGuide(data);const key=guideKey(data);let i=destinations.findIndex(x=>guideKey(x)===key);if(i<0)i=destinations.findIndex(x=>norm(x.country)===norm(data.country)&&norm(x.region)===norm(data.region)&&norm(x.destination)===norm(data.destination));if(i<0){data.imported_at=new Date().toISOString();destinations.push(data);return "neu"}const before=JSON.stringify(destinations[i]);destinations[i]=mergeGuide(destinations[i],{...data,imported_at:new Date().toISOString()});return before===JSON.stringify(destinations[i])?"unverändert":"aktualisiert"}
function upsertTrip(data){const key=tripKey(data);let i=trips.findIndex(x=>tripKey(x)===key);if(i<0){data.imported_at=new Date().toISOString();trips.push(data);return "neu"}const old=trips[i];trips[i]={...old,...data,documents:data.documents||old.documents||[],destination_ids:data.destination_ids||old.destination_ids||[],imported_at:new Date().toISOString()};return "aktualisiert"}
async function importFiles(files){const counts={neu:0,aktualisiert:0,"unverändert":0,fehler:0};for(const f of files){try{const name=f.name.toLowerCase();if(name.endsWith(".zip")){const z=await JSZip.loadAsync(f);for(const [n,e] of Object.entries(z.files)){if(e.dir)continue;const blob=await e.async("blob");await importFiles([new File([blob],n)])}}else if(name.endsWith(".gpx")){toast("Öffne zuerst eine konkrete Wanderung und füge das GPX dort hinzu.")}else{const data=JSON.parse(await f.text());let r;if(data.format==="hikingguide")r=upsertGuide(data);else if(data.format==="travelplan")r=upsertTrip(data);else if(data.format==="trailguide_backup"||data.format==="trailguide-backup"){if(data.destinations)destinations=data.destinations;if(data.trips)trips=data.trips;r="aktualisiert"}else throw new Error("Unbekanntes TrailGuide-Format");counts[r]++}}catch(e){console.error(e);counts.fehler++}}save();showDialog("Import abgeschlossen",`<div class="status-card"><b>${counts.neu} neu · ${counts.aktualisiert} aktualisiert · ${counts["unverändert"]} unverändert</b><span>${counts.fehler?counts.fehler+" Fehler. ":""}Bestehende Guides werden anhand stabiler IDs erkannt. Vorhandene GPX-Tracks und Drive-Verknüpfungen bleiben bei Updates erhalten.</span></div><div class="btnrow"><button class="primary" id="importDone">OK</button></div>`);$("#importDone").onclick=closeDialog}
$("#importInput").onchange=e=>{importFiles([...e.target.files]);e.target.value=""};
async function exportBackup(){const blob=new Blob([JSON.stringify({format:"trailguide_backup",format_version:3,exported_at:new Date().toISOString(),app_version:C.APP_VERSION,destinations,trips},null,2)],{type:"application/json"});download(blob,`TrailGuide_Backup_${new Date().toISOString().slice(0,10)}.json`)}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

let pendingGPX={};
function attachGPX(did,rid=""){pendingGPX={did,rid};$("#gpxInput").click()}
$("#gpxInput").onchange=async e=>{const f=e.target.files[0];e.target.value="";if(!f)return;try{const d=destinations.find(x=>x.id===pendingGPX.did);const r=pendingGPX.rid?d?.routes?.find(x=>x.id===pendingGPX.rid):null;if(!r)throw new Error("Bitte GPX über eine konkrete Wanderung hinzufügen.");const text=await f.text();const geom=parseGPX(text);r.gpx_geometry=geom;r.gpx_original=text;r.gpx_file_name=f.name;r.start={...(r.start||{}),lat:geom[0][0],lng:geom[0][1]};const last=geom[geom.length-1];r.end={...(r.end||{}),name:r.end?.name||"Ziel",lat:last[0],lng:last[1]};r.updated_at=new Date().toISOString();
  let driveSaved=false;
  try{if(window.TrailGuideDrive?.isConnected?.()){r.gpx_drive=await window.TrailGuideDrive.uploadGPX({destination:d,route:r,file:f});driveSaved=true}}catch(err){console.warn("Drive upload skipped",err)}
  save();toast(driveSaved?`GPX importiert (${geom.length} Punkte) und auf Drive gesichert`:`GPX lokal importiert (${geom.length} Punkte)`);openRoute(d.id,r.id)
}catch(err){toast(err.message);console.error(err)}};

let pendingDoc={};function uploadDocument(type,id){pendingDoc={type,id};$("#documentInput").click()}
$("#documentInput").onchange=async e=>{const files=[...e.target.files];e.target.value="";if(!files.length)return;try{for(const f of files){if(!window.TrailGuideDrive?.uploadDocument)throw new Error("Google Drive ist nicht verfügbar.");const saved=await window.TrailGuideDrive.uploadDocument({type:pendingDoc.type,id:pendingDoc.id,file:f,destinations,trips});if(pendingDoc.type==="trip"){const t=trips.find(x=>x.id===pendingDoc.id);t.documents??=[];t.documents.push(saved)}else{const d=destinations.find(x=>x.id===pendingDoc.id);d.documents??=[];d.documents.push(saved)}}save();toast("Dokument auf Google Drive gespeichert");pendingDoc.type==="trip"?openTrip(pendingDoc.id):openDestination(pendingDoc.id)}catch(err){toast(err.message);console.error(err)}};



function shareSnapshot(selectedDestIds,selectedTripIds){
  let selectedTrips=trips.filter(t=>selectedTripIds.includes(t.id));
  const linkedIds=new Set(selectedTrips.flatMap(t=>t.destination_ids||[]));
  const ids=new Set([...selectedDestIds,...linkedIds]);
  const selectedDestinations=destinations.filter(d=>ids.has(d.id));
  selectedTrips=selectedTrips.map(t=>({...t,destination_ids:(t.destination_ids||[]).filter(id=>ids.has(id))}));
  return {schema:3,destinations:selectedDestinations,trips:selectedTrips,state:{}};
}
function openShareDialog(){
  if(SHARE_ID){toast("Du bist bereits in einer freigegebenen Ansicht.");return}
  const destList=destinations.map(d=>`<label class="share-check"><input class="shareDest" type="checkbox" value="${esc(d.id)}" checked><span><b>${esc(d.country)} · ${esc(d.region)} · ${esc(d.destination)}</b><small>${d.routes?.length||0} Wanderungen · ${(d.routes||[]).filter(r=>validGeom(r.gpx_geometry)).length} GPX-Tracks</small></span></label>`).join("")||'<p class="muted">Keine Wanderziele vorhanden.</p>';
  const tripList=trips.map(t=>`<label class="share-check"><input class="shareTrip" type="checkbox" value="${esc(t.id)}" checked><span><b>${esc(t.name)}</b><small>${esc(t.start_date||"")} ${t.end_date?`→ ${esc(t.end_date)}`:""}</small></span></label>`).join("")||'<p class="muted">Keine Reisen vorhanden.</p>';
  showDialog("Freigabelink erstellen",`
    <div class="status-card"><b>Nur Link senden</b><span>Der Empfänger öffnet die normale TrailGuide-Web-App. Deine ausgewählten Inhalte sind bereits geladen; es ist kein Import und keine Installation nötig.</span></div>
    <div class="form-grid" style="margin-top:10px">
      <label class="field full"><span>Name / Bezeichnung der Freigabe</span><input id="shareTitle" placeholder="z. B. Müller · Tessin Wanderungen"></label>
    </div>
    <div class="section-head" style="margin-top:16px"><h2>Wanderziele</h2><div class="btnrow"><button class="secondary" id="shareDestAll">Alle</button><button class="secondary" id="shareDestNone">Keine</button></div></div>
    <div class="share-checklist">${destList}</div>
    <div class="section-head" style="margin-top:16px"><h2>Reisen</h2><div class="btnrow"><button class="secondary" id="shareTripAll">Alle</button><button class="secondary" id="shareTripNone">Keine</button></div></div>
    <div class="share-checklist">${tripList}</div>
    <div class="btnrow"><button class="primary" id="createShareLink">Freigabelink erstellen</button></div>
  `);
  $("#shareDestAll").onclick=()=>$$(".shareDest").forEach(x=>x.checked=true);
  $("#shareDestNone").onclick=()=>$$(".shareDest").forEach(x=>x.checked=false);
  $("#shareTripAll").onclick=()=>$$(".shareTrip").forEach(x=>x.checked=true);
  $("#shareTripNone").onclick=()=>$$(".shareTrip").forEach(x=>x.checked=false);
  $("#createShareLink").onclick=async()=>{
    try{
      if(!window.TrailGuideCloud?.isSignedIn)throw new Error("Bitte zuerst bei TrailGuide Cloud anmelden.");
      const selectedDestIds=$$(".shareDest:checked").map(x=>x.value);
      const selectedTripIds=$$(".shareTrip:checked").map(x=>x.value);
      if(!selectedDestIds.length&&!selectedTripIds.length)throw new Error("Wähle mindestens ein Ziel oder eine Reise.");
      const title=$("#shareTitle").value.trim()||"TrailGuide Freigabe";
      const snapshot=shareSnapshot(selectedDestIds,selectedTripIds);
      const res=await window.TrailGuideCloud.publishShare({title,snapshot});
      showDialog("Freigabelink bereit",`
        <div class="status-card"><b>${esc(title)}</b><span>Jeder mit diesem Link kann die freigegebene TrailGuide-Bibliothek öffnen.</span></div>
        <div class="share-link-box" id="shareUrlBox">${esc(res.url)}</div>
        <div class="btnrow">
          <button class="primary" id="copyShareUrl">Link kopieren</button>
          <button class="secondary" id="nativeShareUrl">Teilen…</button>
          <a class="secondary" target="_blank" rel="noopener" href="${esc(res.url)}">Testen ↗</a>
        </div>
      `);
      $("#copyShareUrl").onclick=async()=>{await navigator.clipboard.writeText(res.url);toast("Link kopiert")};
      $("#nativeShareUrl").onclick=async()=>{if(navigator.share)await navigator.share({title,url:res.url});else{await navigator.clipboard.writeText(res.url);toast("Link kopiert")}};
    }catch(e){console.error(e);toast(e.message||"Freigabelink konnte nicht erstellt werden")}
  };
}
$("#shareLinkButton").onclick=openShareDialog;

function replaceFromShare(data,meta={}){
  window.__tgApplyingCloud=true;
  try{
    destinations=data.destinations||[];
    trips=data.trips||[];
    state={...(data.state||{}),shared:true,share_title:meta.title||"",shared_at:meta.publishedAt||""};
    jset("destinations",destinations);jset("trips",trips);jset("state",state);renderAll();
    let banner=document.querySelector(".share-banner");
    if(!banner){
      banner=document.createElement("div");banner.className="share-banner";
      document.querySelector("main")?.prepend(banner);
    }
    banner.innerHTML=`<span>🔗</span><span><b>${esc(meta.title||"Freigegebener TrailGuide")}</b><small>Freigabelink · vollständige App-Funktionen · eigene lokale Änderungen bleiben auf diesem Gerät</small></span>`;
  }finally{window.__tgApplyingCloud=false}
}

function replaceFromCloud(data){window.__tgApplyingCloud=true;try{if(data.destinations)destinations=data.destinations;if(data.trips)trips=data.trips;if(data.state)state=data.state;jset("destinations",destinations);jset("trips",trips);jset("state",state);renderAll()}finally{window.__tgApplyingCloud=false}}
function getCloudData(){return {schema:3,destinations,trips,state}}
window.TrailGuide={openDestination,openRoute,addRoute,attachGPX,uploadDocument,openTrip,editTrip:id=>editTrip(trips.find(x=>x.id===id)),linkDestination,getCloudData,replaceFromCloud,replaceFromShare,renderAll:()=>renderAll()};
function renderAll(){renderHome();renderDestinations();renderTrips()}renderAll();
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(console.warn));
})();