import{initializeApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";import{getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged,setPersistence,browserLocalPersistence}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";import{initializeFirestore,getFirestore,persistentLocalCache,persistentMultipleTabManager,doc,getDoc,setDoc,serverTimestamp,onSnapshot}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const C=window.TRAILGUIDE_CONFIG,$=s=>document.querySelector(s);const app=initializeApp(C.FIREBASE,'trailguide-app');const auth=getAuth(app);let db;try{db=initializeFirestore(app,{localCache:persistentLocalCache({tabManager:persistentMultipleTabManager()})})}catch(e){db=getFirestore(app)}await setPersistence(auth,browserLocalPersistence);const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});let user=null,unsub=null,busy=false;
function ref(){return user?doc(db,C.FIRESTORE_ROOT,user.uid,'library','main'):null}function render(){const s=$('#cloudAuthStatus'),t=$('#cloudAuthButtonTitle'),txt=$('#cloudAuthButtonText'),sync=$('#cloudSyncStatus');if(!s)return;if(user){s.innerHTML=`<b>${user.displayName||user.email}</b><span>${user.email||''}</span>`;t.textContent='Sign out';txt.textContent='TrailGuide Cloud is connected';sync.innerHTML='<b>Cloud sync</b><span>Realtime sync active for this account.</span>'}else{s.innerHTML='<b>Cloud account</b><span>Not signed in.</span>';t.textContent='Sign in with Google';txt.textContent='Connect this device to TrailGuide Cloud';sync.innerHTML='<b>Cloud sync</b><span>Sign in to activate sync.</span>'}window.TrailGuideCloud={auth,db,user,isSignedIn:!!user};window.TrailGuideDrive?.renderStatus?.()}
async function push(){if(!user||busy)return;busy=true;try{await setDoc(ref(),{schema:1,data:window.TrailGuide.getCloudData(),updatedAt:serverTimestamp()},{merge:true})}finally{busy=false}}
async function pull(){if(!user)return;const s=await getDoc(ref());if(s.exists()&&s.data()?.data)window.TrailGuide.replaceFromCloud(s.data().data);else await push()}
function listen(){if(unsub){unsub();unsub=null}if(!user)return;unsub=onSnapshot(ref(),s=>{if(!busy&&s.exists()&&s.data()?.data)window.TrailGuide.replaceFromCloud(s.data().data)},console.warn)}
$('#cloudAuthButton').onclick=async()=>{try{if(user)await signOut(auth);else await signInWithPopup(auth,provider)}catch(e){window.toast(e.message)}};$('#cloudSyncButton').onclick=async()=>{try{await push();window.toast('Cloud sync complete')}catch(e){window.toast(e.message)}};
window.addEventListener('trailguide:localchange',()=>{if(user&&!busy){clearTimeout(window.__tgPush);window.__tgPush=setTimeout(()=>push().catch(console.warn),900)}});
onAuthStateChanged(auth,async u=>{user=u;render();if(user){await pull();listen()}else if(unsub){unsub();unsub=null}});render();
