(()=>{const C=window.TRAILGUIDE_CONFIG,P=C.LOCAL_PREFIX;let token="",expiry=0,client=null,root=null;const $=s=>document.querySelector(s);function connected(){return !!token&&Date.now()<expiry-60000}function state(k,v){if(arguments.length===1){try{return JSON.parse(localStorage.getItem(P+k)||"null")}catch(e){return null}}localStorage.setItem(P+k,JSON.stringify(v))}function q(s){return String(s||"").replace(/\\/g,"\\\\").replace(/'/g,"\\'")}function clean(s){return String(s||"").replace(/[\\/]+/g," – ").replace(/\s+/g," ").trim()||"Eintrag"}
async function loadGIS(){if(window.google?.accounts?.oauth2)return;await new Promise((res,rej)=>{const s=document.createElement("script");s.src="https://accounts.google.com/gsi/client";s.async=true;s.onload=res;s.onerror=()=>rej(new Error("Google Identity Services konnten nicht geladen werden"));document.head.appendChild(s)})}
async function auth(force=false){if(connected())return token;if(!window.TrailGuideCloud?.isSignedIn)throw new Error("Bitte zuerst bei TrailGuide Cloud anmelden.");await loadGIS();return new Promise((res,rej)=>{client=google.accounts.oauth2.initTokenClient({client_id:C.GOOGLE_DRIVE_CLIENT_ID,scope:C.GOOGLE_DRIVE_SCOPE,include_granted_scopes:true,hint:window.TrailGuideCloud?.user?.email||undefined,callback:r=>{if(r.error){rej(new Error(r.error_description||r.error));return}token=r.access_token;expiry=Date.now()+(r.expires_in||3600)*1000;state("drive_connected",{at:new Date().toISOString()});render();res(token)},error_callback:e=>rej(new Error(e?.message||e?.type||"Drive-Autorisierung fehlgeschlagen"))});client.requestAccessToken({prompt:force||!state("drive_connected")?"consent":""})})}
async function api(url,opt={}){if(!connected())await auth();const h=new Headers(opt.headers||{});h.set("Authorization",`Bearer ${token}`);const r=await fetch(url,{...opt,headers:h});if(!r.ok){let m="";try{m=(await r.json()).error?.message||""}catch(e){}throw new Error(m||`Drive-Fehler ${r.status}`)}if(r.status===204)return null;return (r.headers.get("content-type")||"").includes("json")?r.json():r}
async function list(query){const p=new URLSearchParams({q:query,spaces:"drive",fields:"files(id,name,mimeType,parents,webViewLink,appProperties,trashed)"});return (await api(`https://www.googleapis.com/drive/v3/files?${p}`)).files||[]}
async function folder(name,parent="root",props={}){const found=(await list(`trashed=false and mimeType='application/vnd.google-apps.folder' and name='${q(name)}' and '${q(parent)}' in parents`))[0];if(found)return found;return api("https://www.googleapis.com/drive/v3/files?fields=id,name,mimeType,parents,webViewLink,appProperties",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,mimeType:"application/vnd.google-apps.folder",parents:[parent],appProperties:props})})}
async function ensureRoot(){await auth();if(root)return root;const cached=state("drive_root");if(cached?.id){try{root=await api(`https://www.googleapis.com/drive/v3/files/${cached.id}?fields=id,name,webViewLink,trashed`);if(!root.trashed)return root}catch(e){}}root=await folder(C.DRIVE_ROOT_NAME,"root",{trailguideType:"root",trailguideVersion:"1"});state("drive_root",root);render();return root}
async function hierarchyForDestination(d){const r=await ensureRoot();const countries=await folder("Laender",r.id,{trailguideType:"countries"});const cf=await folder(`${d.country_code||""}_${clean(d.country)}`.replace(/^_/,""),countries.id,{trailguideType:"country"});const rf=await folder(clean(d.region||"Andere"),cf.id,{trailguideType:"region"});return folder(clean(d.destination),rf.id,{trailguideType:"destination",trailguideId:d.id})}
async function hierarchyForTrip(t){const r=await ensureRoot();const tf=await folder("Reisen",r.id,{trailguideType:"trips"});return folder(clean(t.name),tf.id,{trailguideType:"trip",trailguideId:t.id})}
async function upload(file,parent,props={}){const meta={name:file.name,parents:[parent],appProperties:props};const boundary="tg_"+Math.random().toString(16).slice(2);const body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(meta)}\r\n--${boundary}\r\nContent-Type: ${file.type||"application/octet-stream"}\r\n\r\n`,file,`\r\n--${boundary}--`]);return api("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,webViewLink,size,modifiedTime,appProperties",{method:"POST",headers:{"Content-Type":`multipart/related; boundary=${boundary}`},body})}
async function uploadGPX({destination,route,file}){const df=await hierarchyForDestination(destination);const gf=await folder("GPX",df.id,{trailguideType:"gpx"});const target=route?await folder(clean(route.name),gf.id,{trailguideType:"route-gpx",trailguideRouteId:route.id}):gf;return upload(file,target.id,{trailguideType:"gpx-file",destinationId:destination.id,routeId:route?.id||""})}
async function uploadDocument({type,id,file,destinations,trips}){let parent;if(type==="trip"){const t=trips.find(x=>x.id===id);parent=await hierarchyForTrip(t)}else{const d=destinations.find(x=>x.id===id);parent=await hierarchyForDestination(d)}const docs=await folder("Dokumente",parent.id,{trailguideType:"documents"});return upload(file,docs.id,{trailguideType:"document",ownerType:type,ownerId:id})}
async function backupLibrary(){const r=await ensureRoot();const b=await folder("Backups",r.id,{trailguideType:"backups"});const data=window.TrailGuide?.getCloudData?.()||{};const f=new File([JSON.stringify({format:"trailguide_backup",format_version:3,exported_at:new Date().toISOString(),app_version:C.APP_VERSION,...data},null,2)],`TrailGuide_Backup_${new Date().toISOString().replace(/[:.]/g,"-")}.json`,{type:"application/json"});return upload(f,b.id,{trailguideType:"backup"})}
function render(){const s=$("#driveStatus"),b=$("#driveConnectTitle"),openBtn=$("#driveRootButton");if(!s)return;if(connected()||state("drive_connected")){s.innerHTML="<b>Google Drive</b><span>Konfiguriert. Dokumente, GPX-Dateien und Backups werden im TrailGuide-Ordner gespeichert.</span>";b.textContent=connected()?"Google Drive verbunden":"Google Drive erneut verbinden";openBtn.style.display="grid"}else{openBtn.style.display="none"}}
$("#driveConnectButton").onclick=async()=>{try{await auth(true);await ensureRoot();window.toast("Google Drive verbunden")}catch(e){window.toast(e.message)}};$("#driveBackupButton").onclick=async()=>{try{await backupLibrary();window.toast("TrailGuide-Backup auf Google Drive gespeichert")}catch(e){window.toast(e.message)}};$("#driveRootButton").onclick=async()=>{try{const r=await ensureRoot();if(r.webViewLink)open(r.webViewLink,"_blank");else open("https://drive.google.com/drive/my-drive","_blank")}catch(e){window.toast(e.message)}};
window.TrailGuideDrive={isConnected:connected,connect:auth,ensureRoot,uploadGPX,uploadDocument,backupLibrary,renderStatus:render};render()})();